### PR TITLE
r.in.pdal: fix integer overflow

### LINKED ISSUE #2840: [Bug] r.in.pdal: apparent integer overflow
**Describe the bug**

`r.in.pdal` crashes with a segmentation fault when rows * cols exceed 2^31 pixels:

**To Reproduce**
```

grassdev ~/grassdata/nc_spm_08_grass7/user1
...
Welcome to GRASS GIS 8.3.dev (20bba91215)
...

# simulate large region
g.region n=18 s=0 w=0 e=18 res=0.00037 -p
projection: 99 (Lambert Conformal Conic)
zone:       0
datum:      nad83
ellipsoid:  a=6378137 es=0.006694380022900787
north:      18
south:      0
west:       0
east:       18
nsres:      0.00037
ewres:      0.00037
rows:       48649
cols:       48649
cells:      2366725201

# use LAZ: docker/testdata/simple.laz
r.in.pdal resolution=0.00037 type=CELL method=percentile pth=95 input=simple.laz output=simple_perc -o
Reading data...
Overriding projection check and assuming that the projection of input
matches the location projection
Running PDAL algorithms...
Scanning points...
Writing output raster map...
Segmentation fault (core dumped)

# debug
GRASS nc_spm_08_grass7/user1:testdata > gdb r.in.pdal
GNU gdb (GDB) Fedora Linux 12.1-7.fc37
...
Reading symbols from r.in.pdal...
(gdb) r resolution=0.00037 type=CELL method=percentile pth=95 input=simple.laz output=simple_perc -o
Starting program: /home/mneteler/software/grass_main/dist.x86_64-pc-linux-gnu/bin/r.in.pdal resolution=0.00037 type=CELL method=percentile pth=95 input=simple.laz output=simple_perc -o
...
Reading data...                                                                                                                                                     
Overriding projection check and assuming that the projection of input
matches the location projection
Running PDAL algorithms...
Scanning points...
Writing output raster map...

Program received signal SIGSEGV, Segmentation fault.
write_percentile (bin_index=0x7fffffffb970, raster_row=0x618760, index_array=0x7ffda3979010, row=0, cols=48649, rtype=0, pth=95) at bin_write.c:212
212	                node_id = ((struct z_node *)bin_index->nodes)[node_id].next;

(gdb) bt full
#0  write_percentile (bin_index=0x7fffffffb970, raster_row=0x618760, index_array=0x7ffda3979010, row=0, cols=48649, rtype=0, pth=95) at bin_write.c:212
        n_offset = 0
        n = 1
        j = -25480
        z = 0
        col = 0
        node_id = 0
        head_id = 0
        r_low = 48
        r_up = -25296
        ptr = 0x618760
#1  0x0000000000424ace in write_values (point_binning=0x7fffffffca80, bin_index_nodes=0x7fffffffb970, raster_row=0x618760, row=0, cols=48649, rtype=0)
    at point_binning.c:372
        ptr = 0x0
        col = 5398200
#2  0x00000000004344f4 in main (argc=8, argv=0x7fffffffd108) at main.cpp:859
        row = 0
        out_fd = 0
        outmap = 0x524d90 "simple_perc"
        rtype = 0
        base_raster_data_type = 32767
        history = {fields = {0x7ffff76326a0 <(anonymous namespace)::num_get_c> "", 0x7fffffffcc30 "\240&c\367\377\177", 
            0x7ffff76326a0 <(anonymous namespace)::num_get_c> "", 0x6 <error: Cannot access memory at address 0x6>, 
            0x1000000006 <error: Cannot access memory at address 0x1000000006>, 0xffffffffffffff98 <error: Cannot access memory at address 0xffffffffffffff98>, 
            0x0, 0x505f48 "\340,c\367\377\177"}, nlines = 5267064, lines = 0x7ffff7631240 <std::clog>}
        title = "\200l?\367\377\177\000\000\240&c\367\377\177\000\000h\250b\367\377\177\000\000\370\\b\367\377\177\000\000\000\000\000\000\000\000\000\000\240]P\000\000\000\000\000(^P\000\000\000\000\000\023\320J\367\377\177\000"
        base_segment = {open = -13536, nrows = 3, ncols = 352193898867, len = 0, srows = 0, scols = -13504, srowscols = 32767, size = 13, spr = 0, 
          spill = 1684104562, fast_adrs = 779317861, scolbits = 431265903213, srowbits = 140737488341856, segbits = 3, fast_seek = 7889510, lenbits = 32512, 
          sizebits = -147702507, address = 0x7ffff73f6c80 <main_arena>, seek = 0x210, fname = 0x70 <error: Cannot access memory at address 0x70>, fd = -146079585, 
          scb = 0x0, load_idx = 0x6f72bc3a9, nfreeslots = -144543768, freeslot = 0x7ffff7625cf8 <typeinfo for std::locale::facet>, agequeue = 0x7fffffffcbc0, 
          youngest = 0xb, oldest = 0x21000, nseg = -1839399936, cur = 1061778566, offset = -13344, cache = 0x210 <error: Cannot access memory at address 0x210>}
        point_binning = {method = 12, bin_n = 0, bin_min = 0, bin_max = 0, bin_sum = 0, bin_m2 = 0, bin_z_index = 1, bin_cnt_index = 0, bin_eigenvalues = 0, 
          bin_coordinates = 0, n_array = 0x0, min_array = 0x0, max_array = 0x0, sum_array = 0x0, c_array = 0x0, mean_array = 0x0, m2_array = 0x0, 
          index_array = 0x7ffda3979010, x_array = 0x0, y_array = 0x0, pth = 95, trim = 6.2564893645348082e-85}
        raster_row = 0x618760
        region = {format = 0, compressed = -1, rows = 48649, rows3 = 1, cols = 48649, cols3 = 1, depths = 1, proj = 99, zone = 0, ew_res = 0.00036999999999999999, 
          ew_res3 = 18, ns_res = 0.00036999999999999999, ns_res3 = 18, tb_res = 1, north = 18.000129999999999, south = 0, east = 18.000129999999999, west = 0, 
          top = 1, bottom = 0}
        input_region = {format = 5239680, compressed = 0, rows = 5, rows3 = 0, cols = -13920, cols3 = 32767, depths = 3, proj = 0, zone = 3618149, 
          ew_res = 6.9533558071484507e-310, ew_res3 = 6.953355807148846e-310, ns_res = 5.434722104253712e-323, ns_res3 = 6.2564893645348082e-85, 
          tb_res = 1.7876031224348603e-317, north = 6.953355807150427e-310, south = 1.4821969375237396e-323, east = 7.0734630506338787e+25, west = 0, 
          top = 6.953355807152008e-310, bottom = 5.434722104253712e-323}
        rows = 48649
        cols = 48649
        buff = '\000' <repeats 1096 times>...
--Type <RET> for more, q to quit, c to continue without paging--c
        bin_index_nodes = {num_nodes = 0, max_nodes = 0, nodes = 0x0}
        loc_wind = {format = 0, compressed = -1, rows = 48649, rows3 = 1, cols = 48649, cols3 = 1, depths = 1, proj = 99, zone = 0, ew_res = 0.00036999732779707703, ew_res3 = 18, ns_res = 0.00036999732779707703, ns_res3 = 18, tb_res = 1, north = 18, south = 0, east = 18, west = 0, top = 1, bottom = 0}
        module = 0x7ffff7ea5f08 <state+40>
        input_opt = 0x7ffff7ea5f68 <state+136>
        output_opt = 0x50dfe0
        file_list_opt = 0x520a50
        method_opt = 0x520b10
        type_opt = 0x521520
        base_raster_opt = 0x5215e0
        zrange_opt = 0x520c60
        zscale_opt = 0x520d20
        irange_opt = 0x520de0
        iscale_opt = 0x520ea0
        drange_opt = 0x520f60
        dscale_opt = 0x521020
        reproject_flag = 0x7ffff7ea5f38 <state+88>
        input_srs_opt = 0x521100
        pth_opt = 0x5211c0
        trim_opt = 0x521280
        res_opt = 0x521340
        return_filter_opt = 0x522dc0
        class_filter_opt = 0x522e80
        dimension_opt = 0x522f40
        user_dimension_opt = 0x523000
        extents_flag = 0x5230c0
        set_region_flag = 0x523110
        over_flag = 0x523160
        base_rast_res_flag = 0x5231b0
        print_info_flag = 0x523200
        print_extent_flag = 0x523250
        infiles = {num_items = 1, max_items = 10, items = 0x5251f0}
        xmin = 0
        ymin = 0
        xmax = 18
        ymax = 18
        use_spatial_filter = true
        zrange_min = 0
        zrange_max = 0
        use_zrange = false
        irange_min = 0
        irange_max = 0
        use_irange = false
        drange_min = 0
        drange_max = 0
        use_drange = false
        return_filter_struct = {filter = 0}
        use_return_filter = true
        class_filter = {str_classes = 0x0}
        use_class_filter = true
        dim_to_import = pdal::Dimension::Id::Z
        zscale = 1
        iscale = 1
        dscale = 1
        output_scale = 1
        res = 0.00036999999999999999
        use_base_raster_res = 0
        readers = std::vector of length 1, capacity 1 = {0x525eb8}
        factory = {m_ownedStages = std::vector of length 1, capacity 1 = {std::unique_ptr<pdal::Stage> = {get() = 0x525eb8}}, m_mutex = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, <No data fields>}}
        merge_filter = <incomplete type>
        last_stage = 0x7fffffffb6a8
        reprojection_filter = <incomplete type>
        grass_filter = {<pdal::Filter> = {<No data fields>}, <pdal::Streamable> = {<No data fields>}, dim_to_import_ = pdal::Dimension::Id::Z, use_spatial_filter_ = true, use_zrange_ = false, use_irange_ = false, use_drange_ = false, xmin_ = 0, xmax_ = 18, ymin_ = 0, ymax_ = 18, zmin_ = 0, zmax_ = 0, imin_ = 0, imax_ = 0, dmin_ = 0, dmax_ = 0, n_processed_ = 1065, n_passed_ = 0, n_outside_ = 1065, zrange_filtered_ = 0, irange_filtered_ = 0, drange_filtered_ = 0, return_filtered_ = 0, n_class_filtered_ = 0, zscale_ = 1, iscale_ = 1, dscale_ = 1, use_class_filter_ = false, class_filter_ = {str_classes = 0x0}, use_return_filter_ = false, return_filter_ = {filter = 0}, base_segment_ = 0x0, input_region_ = 0x0, base_raster_data_type_ = 0}
        binning_writer = {<pdal::Writer> = {<No data fields>}, <pdal::Streamable> = {<No data fields>}, n_processed = 0, region_ = 0x7fffffffca00, point_binning_ = 0x7fffffffca80, bin_index_nodes_ = 0x7fffffffb970, rtype_ = 0, cols_ = 48649, scale_ = 1, dim_to_import_ = pdal::Dimension::Id::Z, base_segment_ = 0x0, input_region_ = 0x0, base_raster_data_type_ = 0}
        point_table_capacity = 10000
        point_table = {<pdal::StreamPointTable> = {<pdal::SimplePointTable> = {<No data fields>}, m_capacity = 10000, m_numPoints = 1065, m_skips = std::vector<bool> of length 10000, capacity 10048 = {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false...}}, m_buf = std::vector of length 520052, capacity 520052 = {0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000'...}, m_layout = <incomplete type>}
        point_layout = 0x7fffffffaf10
        file_list = '\000' <repeats 4095 times>
(gdb) 
```

**Expected behavior**

No segfault.

**System description (please complete the following information):**

- Operating System: Fedora 37
- GRASS GIS version: current 8.3.x

### PR DESCRIPTION
**Pull request by nilason**
Fixes #2840

The segmentation fault reported with #2840 is caused by a call to `Rast_set_null_value()` where the parameter `numVals` is defined as integer. Overflow occurs if the `col * row` value given to numVals exceeds INT_MAX.

I put this up initially as a draft as this brings up some questions:

**Firstly:**
The array is allocated as `rows * (cols + 1)`:

https://github.com/OSGeo/grass/blob/b06c460733829cac9a79265b0760441be130edd8/raster/r.in.pdal/point_binning.c#L251-L252

but zeroed as `rows * cols`:
https://github.com/OSGeo/grass/blob/b06c460733829cac9a79265b0760441be130edd8/raster/r.in.pdal/point_binning.c#L60

Is this really by design?

**Secondly:**

The question is whether `Rast_set_null_value()` family of functions should _all_ be changed accordingly and to what type. I have now changed `numVals` to `unsigned int`, but this could be `size_t`, `unsigned long` ...
Or do we re-implement this function locally within r.in.pdal and leave lib/raster as is?

### CODE REVIEW

File: include/grass/defs/raster.h [hunk 1]
```diff
@@ -406,8 +406,8 @@ int Rast_maskfd(void);
     (*(const DCELL *)(dcellVal) != *(const DCELL *)(dcellVal))
 
 void Rast__set_null_value(void *, int, int, RASTER_MAP_TYPE);
-void Rast_set_null_value(void *, int, RASTER_MAP_TYPE);
-void Rast_set_c_null_value(CELL *, int);
+void Rast_set_null_value(void *, unsigned int, RASTER_MAP_TYPE);
+void Rast_set_c_null_value(CELL *, unsigned int);
```
Comment (metzm) [inline include/grass/defs/raster.h:410]: `unsigned int` is not large enough (below you use size_t), and since `Rast_set_null_value()` calls `Rast_set_[c|f|d]_null_value()`, the defs must all be the same.

File: raster/r.in.pdal/point_binning.c [hunk 2]
```diff
@@ -57,7 +57,7 @@ int blank_array(void *array, int nrows, int ncols, RASTER_MAP_TYPE map_type,
     case -1:
         /* fill with NULL */
         /* alloc for col+1, do we come up (nrows) short? no. */
-        Rast_set_null_value(array, nrows * ncols, map_type);
+        Rast_set_null_value(array, (size_t)nrows * ncols, map_type);
```
Comment (metzm) [inline raster/r.in.pdal/point_binning.c:60]: `size_t` on 64 bit systems is larger than `unsigned int`, this will not work for larger regions.

I would rather loop over the rows and set each row to NULL. A pointer can be used to go over the rows, increased with `ptr = G_incr_void_ptr(ptr, ncols * map_type_size)`:

```
        for (row = 0; row < nrows; row++) {
            Rast_set_null_value(ptr, ncols, map_type);
            ptr = G_incr_void_ptr(ptr, ncols * Rast_cell_size(map_type));
        }
```

Comment (wenzeslaus) [reply raster/r.in.pdal/point_binning.c:60]: While "set whole raster map to null" seems like a good function to have, I'm afraid that the correct way of using _Rast_set_null_value_ is to set only up a row of value as @metzm  says.

**Comment by wenzeslaus** [comment]
> ...The array is allocated as rows * (cols + 1)...but zeroed as rows * cols... Is this really by design?

The history of the code is that I took the point binning code from the original r.in.lidar which likely took it from r.in.xyz. While I was trying to improve the API when working on r.in.lidar, I think I assumed the code to be correct and extra allocated space would pass any automated checks. So, from this point of view, it is likely not intentional. By quick look into the code I don't see anything either, but perhaps a second look would be good.

Both "null whole raster map" and point/value binning would be good to have in the library, but that's a different story.

File: raster/r.in.pdal/point_binning.c (hunk 2 above)
Comment (nilason) [reply raster/r.in.pdal/point_binning.c:60]: With the change @metzm suggested, I guess there is no need to change (at this time) `Rast_set_null_value()`?

Comment (metzm) [reply raster/r.in.pdal/point_binning.c:60]: "Set whole raster map to null" would be a rather special function because typically raster data are accessed by rows and not as a whole. Standard procedure would be e.g. to set the next output row to NULL, do some calculations with input data, set data in the output row where applicable, write output row, continue with next row.

In order to save memory consumption, raster operations should wherever possible never load a whole raster to memory but instead proceed row by row or a small chunk of rows (e.g. r.neighbors). This is IMHO a big strength of GRASS, also for cloud and grid computing.

Comment (nilason) [reply raster/r.in.pdal/point_binning.c]: Just pushed the suggested changes. Please review!

**Review by metzm — APPROVED** [review]

**Comment by nilason** [comment]
Thank you both for your input and in particular for the brilliant solution @metzm !

Shall this be backported?

**Comment by neteler** [comment]
> Shall this be backported?

Yes please.

**Comment by petrasovaa** [comment]
There is identical code in r.in.xyz as Vashek points out:

https://github.com/OSGeo/grass/blob/main/raster/r.in.xyz/support.c#L48

**Comment by nilason** [comment]
> There is identical code in r.in.xyz as Vashek points out:
> 
> https://github.com/OSGeo/grass/blob/main/raster/r.in.xyz/support.c#L48

Thanks! I'll get to it.

**Comment by nilason** [comment]
> > There is identical code in r.in.xyz as Vashek points out:
> > https://github.com/OSGeo/grass/blob/main/raster/r.in.xyz/support.c#L48
> 
> Thanks! I'll get to it.

Done with #2847

**Comment by metzm** [comment]
There are a number of modules with shared code base such as `r.in.xyz` and `r.in.pdal`. In order to ease maintenance, it would be great to add some comment in the code for developers at a prominent place to keep shared code in sync. I tried to do this e.g. for the GDAL/OGR import modules `r.in.gdal`, `r.external`, `v.in.ogr`, `v.external`.

**Comment by nilason** [comment]
> There are a number of modules with shared code base such as `r.in.xyz` and `r.in.pdal`. In order to ease maintenance, it would be great to add some comment in the code for developers at a prominent place to keep shared code in sync. I tried to do this e.g. for the GDAL/OGR import modules `r.in.gdal`, `r.external`, `v.in.ogr`, `v.external`.

Good point!

**Comment by wenzeslaus** [comment]
In case of r.in.xyz and r.in.pdal, an actual library might be more appropriate. However, as a simple fix, we now have also enforcement of duplicate files to be the same: https://github.com/OSGeo/grass/commit/8b6cd9423b5800ade1b1d0d5f8aed7c4b6489e85

**Comment by nilason** [comment]
> In case of r.in.xyz and r.in.pdal, an actual library might be more appropriate. However, as a simple fix, we now have also enforcement of duplicate files to be the same: [8b6cd94](https://github.com/OSGeo/grass/commit/8b6cd9423b5800ade1b1d0d5f8aed7c4b6489e85)

They are not duplicate files, r.in.pdal is, as far as I can tell, heavily refactored too. Library functions for repetitive code sounds better, if practical.
