### PR TITLE
lib: fix reading GRASS vrts with multiple threads

### LINKED ISSUE #6616: [Bug] r.patch fails if one input is a GRASS vrt and nprocs > 1
## Describe the bug
It seems there is a race condition with parallelised `r.patch` in G85 if one input is a GRASS vrt consisting of many files, the error is "Invalid descriptor: X" coming from https://github.com/OSGeo/grass/blob/main/lib/raster/close.c#L104. It works with `nprocs=1`. In a GRASS vrt, the source raster maps are opened and closed on demand in order to avoid issues like in #6615.

## To reproduce
1. Create a GRASS vrt with `r.buildvrt` consisting of a large number of files
2. Use a fast CPU with at least 6 cores (not threads but real cores)
3. Patch the GRASS vrt with another raster map using the max number of available threads 

## Solution
For parallelisation, some sort of file open/close lock needs to be implemented in `/lib/raster`

## System description
G85

## Additional context
Attempting to patch the results of AI models for semantic segmentation which require small input tiles of typically the size 256x256 pixels to 512x512 pixels.

### PR DESCRIPTION
**Pull request by metzm**
# Description
Parallelised reading of the real raster maps constituting a GRASS virtual raster causes IO read errors and segmentation faults. This PR enforces reading of the different rasters in only one thread.

Someone with better knowledge of OpenMP directives than me should have a look at this PR. At least for me this PR fixes the read errors.

# How to reproduce
1. create tiles with  `r.tile`
2. build a GRASS vrt from these tiles with `r.buildvrt`
3. run `r.univar` on this vrt with nprocs > 1

This also fixes #6616

### CODE REVIEW

File: lib/raster/vrt.c
Comment (wenzeslaus) [inline lib/raster/vrt.c]: Delay the assignment to have it in the critical block. fcb is used only once, so we can just do it inline.

```suggestion
struct R_vrt *vrt;
struct tileinfo *ti;
```

Comment (wenzeslaus) [inline lib/raster/vrt.c:181]:
```suggestion

    // R__.fileinfo can be reallocated by concurrent open/close calls,
    // se we extract the vrt pointer under the same lock that protects the I/O below.
    // This expects callers to open the raster once per thread before
    // entering any parallel code.
#pragma omp critical(raster_vrt_read)
    {
        vrt = R__.fileinfo[fd].vrt;
    }
    ti = vrt->tileinfo;

```

File: lib/raster/vrt.c [hunk 1]
```diff
@@ -187,6 +187,11 @@ int Rast_get_vrt_row(int fd, void *buf, int row, RASTER_MAP_TYPE data_type)
     tmpbuf = Rast_allocate_input_buf(data_type);
     have_tile = 0;
 
+    /* parallelised reading of the real raster maps
+     * constituting a GRASS virtual raster
+     * causes IO read errors and segmentation faults:
+     * enforce reading of the different rasters in only one thread */
+#pragma omp critical
```
Comment (wenzeslaus) [inline lib/raster/vrt.c]: It is the access to R__.fileinfo, so I think the comment can be more specific (reading as in getting the raw row is okay).

```suggestion
    // Serialize the entire open/read/close cycle for each tile
    // because they all access the non-thread-safe global R__.fileinfo array.
#pragma omp critical(raster_vrt_read)
```

(We can no use the `//` comments - C99.)

**Comment by metzm** [comment]
Thanks for your suggestion to also protect `R__.fileinfo`. Applied with slight modifications

**Comment by nilason** [comment]
@metzm Please go ahead and and merge if you like, the 8.5 release is approaching.

**Comment by metzm** [comment]
backported to G85 and G84
