### PR TITLE
lib: Replace deprecated gets() with fgets() in test files

### LINKED ISSUE #7096: [Bug] Replace deprecated gets() with fgets() in test files
## Describe the bug
The gets() function was removed from the C11 standard (ISO/IEC 9899:2011) due to its inherent buffer overflow vulnerability — it provides no way to specify the buffer size. Two test files in the codebase currently use gets(), which poses a security risk and prevents compilation with stricter C standards.

Affected files:

lib/btree/test/try.c
lib/linkm/test/try2.c

## To reproduce
Inspect the source code of the affected files mentioned above.
Observe calls to gets(key), gets(data), and gets(buf).

## Expected behavior
The codebase should use safer alternatives like fgets() which allow specifying the buffer size to prevent buffer overflows.

## System description
Operating System: Linux (WSL Ubuntu)
GRASS version: 8.6.0dev

## Additional context
The proposed fix involves replacing gets(str) with fgets(str, sizeof(str), stdin) and using strcspn() to strip the trailing newline character, which fgets retains but gets does not.

This change also includes minor cleanups:

lib/linkm/test/try2.c
: Added missing #include <stdlib.h> and #include <string.h>, removed deprecated register keyword.
lib/btree/test/try.c
: Added missing #include <stdlib.h>.
Updated exit(0) to exit(EXIT_SUCCESS) in both files per GRASS coding style guidelines.

### PR DESCRIPTION
**Pull request by HUN-sp**
Fixes #7096

### CODE REVIEW

**Comment by HUN-sp** [comment]
Hi @petrasovaa,

​I would really appreciate a review on this.
​Regarding my previous PR #7044: After the initial concerns about AI usage, I put in a lot of manual effort to completely refactor and fix it, ensuring it met the project's standards. 

​I am very committed to contributing high-quality code to this organization for GSoC. Could you please let me know if there are any issues I need to address?

**Comment by nilason** [comment]
Although the update itself seems ok, I wonder if you tried to compile the file at all. It errored out for me with Clang.

**Comment by HUN-sp** [comment]
Hi @nilason, thanks for the review!

I tested compilation with GCC and the warnings I see (incompatible pointer types, implicit function declarations in `try2.c`) are all pre-existing in the original code — none were introduced by this PR. I verified by compiling both the original and modified files and the warnings are identical. These test files don't have a **Makefile** and aren't part of the build system, which is why CI passes. Could you share the specific error you're seeing with Clang? I'd be happy to address it if it's related to my changes, or file a separate issue if it's pre-existing.

**Comment by nilason** [comment]
These test were [removed from Makefiles in 2008](https://github.com/OSGeo/grass/commit/1292bf9a1eeac4671dc179ef3b08470b25c5e2e5#diff-f905d4bae181435b740781a1200795932719553215763bad87636d6322e42238), with the release of GRASS 7.8, as they were already then considered "dead code". They originate, at the latest, in the early 90's and haven't probably been used much since. So updating them to modern code is more of an exercise than of practical importance. Until someone in the team votes for removing the files, let us make it an exercise (and only replacing gets() doesn't make much sense in this situation). Below are the logs for compilation with Clang:


```
clang /grass/lib/btree/test/try.c -I/grassbuild/output/lib/grass86/include -L/grassbuild/output/lib/grass86/lib -lgrass_btree
/grass/lib/btree/test/try.c:32:22: error: incompatible function pointer types passing 'int (const char *, const char *)' to parameter of type 'int (*)(const void *, const void *)' [-Wincompatible-function-pointer-types]
   32 |     btree_create(&B, strcmp, 10);
      |                      ^~~~~~
/grassbuild/output/lib/grass86/include/grass/defs/btree.h:5:33: note: passing argument to parameter here
    5 | int btree_create(BTREE *, int (*)(const void *, const void *), int);
      |                                 ^
/grass/lib/btree/test/try.c:35:14: warning: 'gets' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of gets(3), it is highly recommended that you use fgets(3) instead. [-Wdeprecated-declarations]
   35 |         if (!gets(key))
      |              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h:260:1: note: 'gets' has been explicitly marked deprecated here
  260 | __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of gets(3), it is highly recommended that you use fgets(3) instead.")
      | ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:227:48: note: expanded from macro '__deprecated_msg'
  227 |         #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
      |                                                       ^
/grass/lib/btree/test/try.c:36:13: error: call to undeclared library function 'exit' with type 'void (int) __attribute__((noreturn))'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   36 |             exit(0);
      |             ^
/grass/lib/btree/test/try.c:36:13: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'
/grass/lib/btree/test/try.c:41:47: warning: format specifies type 'char *' but the argument has type 'void *' [-Wformat]
   41 |             fprintf(stdout, "%s = %s\n", key, d);
      |                                   ~~          ^
/grass/lib/btree/test/try.c:46:14: warning: 'gets' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of gets(3), it is highly recommended that you use fgets(3) instead. [-Wdeprecated-declarations]
   46 |         if (!gets(data))
      |              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h:260:1: note: 'gets' has been explicitly marked deprecated here
  260 | __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of gets(3), it is highly recommended that you use fgets(3) instead.")
      | ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:227:48: note: expanded from macro '__deprecated_msg'
  227 |         #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
      |                                                       ^
3 warnings and 2 errors generated.
```

```
clang /grass/lib/linkm/test/try2.c -I/grassbuild/output/lib/grass86/include -L/grassbuild/output/lib/grass86/lib -lgrass_linkm
/grass/lib/linkm/test/try2.c:39:20: warning: 'gets' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of gets(3), it is highly recommended that you use fgets(3) instead. [-Wdeprecated-declarations]
   39 |     while (NULL != gets(buf)) {
      |                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h:260:1: note: 'gets' has been explicitly marked deprecated here
  260 | __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of gets(3), it is highly recommended that you use fgets(3) instead.")
      | ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:227:48: note: expanded from macro '__deprecated_msg'
  227 |         #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
      |                                                       ^
/grass/lib/linkm/test/try2.c:41:43: warning: incompatible pointer types passing 'char *' to parameter of type 'struct link_head *' [-Wincompatible-pointer-types]
   41 |             tmp = (struct link *)link_new(head);
      |                                           ^~~~
/grassbuild/output/lib/grass86/include/grass/defs/linkm.h:17:36: note: passing argument to parameter here
   17 | VOID_T *link_new(struct link_head *);
      |                                    ^
/grass/lib/linkm/test/try2.c:44:17: error: call to undeclared function 'add_link_rev'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   44 |                 add_link_rev(&List, tmp);
      |                 ^
/grass/lib/linkm/test/try2.c:46:17: error: call to undeclared function 'add_link'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   46 |                 add_link(&List, tmp);
      |                 ^
/grass/lib/linkm/test/try2.c:49:9: error: call to undeclared function 'dumplist'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   49 |         dumplist(&List);
      |         ^
/grass/lib/linkm/test/try2.c:55:26: warning: incompatible pointer types passing 'char *' to parameter of type 'struct link_head *' [-Wincompatible-pointer-types]
   55 |             link_dispose(head, p);
      |                          ^~~~
/grassbuild/output/lib/grass86/include/grass/defs/linkm.h:8:37: note: passing argument to parameter here
    8 | void link_dispose(struct link_head *, VOID_T *);
      |                                     ^
/grass/lib/linkm/test/try2.c:55:32: warning: incompatible pointer types passing 'struct link *' to parameter of type 'char *' [-Wincompatible-pointer-types]
   55 |             link_dispose(head, p);
      |                                ^
/grassbuild/output/lib/grass86/include/grass/defs/linkm.h:8:47: note: passing argument to parameter here
    8 | void link_dispose(struct link_head *, VOID_T *);
      |                                               ^
/grass/lib/linkm/test/try2.c:61:18: warning: incompatible pointer types passing 'char *' to parameter of type 'struct link_head *' [-Wincompatible-pointer-types]
   61 |     link_cleanup(head);
      |                  ^~~~
/grassbuild/output/lib/grass86/include/grass/defs/linkm.h:14:37: note: passing argument to parameter here
   14 | void link_cleanup(struct link_head *);
      |                                     ^
/grass/lib/linkm/test/try2.c:63:5: error: call to undeclared library function 'exit' with type 'void (int) __attribute__((noreturn))'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   63 |     exit(0);
      |     ^
/grass/lib/linkm/test/try2.c:63:5: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'
/grass/lib/linkm/test/try2.c:66:6: error: conflicting types for 'add_link_rev'
   66 | void add_link_rev(struct link *List, struct link *link)
      |      ^
/grass/lib/linkm/test/try2.c:44:17: note: previous implicit declaration is here
   44 |                 add_link_rev(&List, tmp);
      |                 ^
/grass/lib/linkm/test/try2.c:75:6: error: conflicting types for 'add_link'
   75 | void add_link(struct link *List, struct link *link)
      |      ^
/grass/lib/linkm/test/try2.c:46:17: note: previous implicit declaration is here
   46 |                 add_link(&List, tmp);
      |                 ^
/grass/lib/linkm/test/try2.c:86:6: error: conflicting types for 'dumplist'
   86 | void dumplist(struct link *List)
      |      ^
/grass/lib/linkm/test/try2.c:49:9: note: previous implicit declaration is here
   49 |         dumplist(&List);
      |         ^
5 warnings and 7 errors generated.
```

**Comment by HUN-sp** [comment]
Hi @nilason,
Thanks for the detailed error log — it made the fixes straightforward to track down. Here's a summary of what was corrected in both files: try.c and try2.c:

Replaced gets() with fgets() + strcspn() to strip the newline (the main security fix)
Added #include <stdlib.h> for exit()
Changed head from VOID_T * / char * to struct link_head * to match the API
Added forward declarations for add_link_rev, add_link, and dumplist before main()
Fixed link_dispose() call to pass correct types (struct link_head * and VOID_T *)
Verified with gcc -Wall -Werror — compiles cleanly with zero warnings and zero errors.

Happy to make any changes if something looks off!

File: lib/linkm/test/try2.c [hunk 1]
```diff
@@ -5,24 +5,25 @@
...
+#include <string.h>
+
 #include <grass/linkm.h>
 
 struct link {
     char let;
     struct link *next;
 };
 
+static void add_link_rev(struct link *List, struct link *link);
```
Comment (nilason) [inline lib/linkm/test/try2.c]: It is custom in GRASS code (although it is not strictly so) to not name the parameters in a function prototype:

```suggestion
static void add_link_rev(struct link *, struct link *);
```

File: lib/linkm/test/try2.c [hunk 2]
```diff
@@ -5,24 +5,25 @@
  **
  */
 
-/*
- **  read from stdin and each line into a linked list of chars
- **  then print it back out.   if there is any argument specified
- **  the lines will be printed out reversed.
- */
-
```
Comment (nilason) [inline lib/linkm/test/try2.c:13]: No need to remove this bloc, is there?

**Review by nilason — CHANGES_REQUESTED** [review]

File: lib/linkm/test/try2.c (hunk 1 above)
Comment (HUN-sp) [reply lib/linkm/test/try2.c]: Done , removed parameter names from all three forward declarations. Thanks for the GRASS convention tip!

File: lib/linkm/test/try2.c (hunk 2 above)
Comment (HUN-sp) [reply lib/linkm/test/try2.c:13]: Restored the comment block

**Comment by HUN-sp** [comment]
Thank you @nilason for the review and guidance!
